### ISSUE TITLE
Bycatch CPUE as a potential index

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/dogfish-assess#12]
Dan Edwards, Brian Mose and Bruce Turris may be helpful to identify season and timing

**Comment by seananderson** [comment]
I have started here: https://github.com/pbs-assess/dogfish-assess/blob/c55a9d0d3503ae70116e02f627b914e7e9ecddc5/analysis/01-cpue-sdmTMB.Rmd#L134-L146

This seems promising and goes back farther. 2023 looks like an anomaly that may be hard to explain with a model.

Will also let me slice an index by different seasons + depths.
