### ISSUE TITLE
Develop an index from the Sablefish trap survey?

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/dogfish-assess#13]
Deeper, more offshore compared to trawl and line surveys

**Comment by seananderson** [comment]
Probably too noisy to fit to, but we may want to include the plot?

**Comment by quang-huynh** [comment]
Yes, a designed based index and plotting the set data (with respect to depth or lat/lon) could suffice

**Comment by seananderson** [comment]
Philina made this plots (axis starts at 1990, goes to 2021/2022?) 
<img width="236" alt="image" src="https://github.com/pbs-assess/dogfish-assess/assets/19349/4ef5abbd-e7b8-43cf-af0c-987b675c6d93">

<img width="389" alt="image" src="https://github.com/pbs-assess/dogfish-assess/assets/19349/5ccd40fe-5870-4153-91d9-fe67cd1ae4f5">
