### ISSUE TITLE
Add recreational catch, survey catch, and any missing bycatch

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/dogfish-assess#14]
- Would use iRec database
- Is it straightforward to calculate survey catch from the current data files?

**Comment by seananderson** [comment]
> Is it straightforward to calculate survey catch from the current data files?

Yes, from trawl survey. HBLL/IPHC is count only so requires assuming an average dogfish? The shrimp survey (multispecies small mesh) may not be included there.

Most importantly:

- [ ] add back in the 3CD catch I lost (current cached data are updated)

**Comment by seananderson** [comment]
@LindsayDavidson has the irec catch, I think

**Comment by seananderson** [comment]
Note from last resdoc: 

> [A Science participant] noted that in particular the directed longline halibut fishery could represent a significant amount of spiny dogfish catch dating to the 1930s which is not well documented

**Comment by LindsayDavidson** [comment]
Added rec, survey catch, bycatch from salmon fisheries between 1998-2011.
