### ISSUE TITLE
Try predicting IPHC index on HBLL grid

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#15]
Is the steep HBLL decline a feature of the hard bottom inshore habitat?

**Comment by seananderson** [comment]
If that does explain most of it, consider combining the two into 1 index.

**Comment by quang-huynh** [comment]
Perhaps assign this to @LindsayDavidson ?

Also look at substrate map. I can work on this picking up from Quillback Rockfish

**Comment by quang-huynh** [comment]
The IPHC index does not appear to change much when predicted on the HBLL grid:

![iphc_index_on_hbll](https://github.com/pbs-assess/dogfish-assess/assets/15094006/87567010-8204-4262-861c-a31ada26591e)
![iphc_hbll_grid](https://github.com/pbs-assess/dogfish-assess/assets/15094006/9520d693-fc37-4382-a776-ac830d9515f7)
![index](https://github.com/pbs-assess/dogfish-assess/assets/15094006/fd99d775-324a-485f-8e76-9f4f52901ccf)

**Comment by seananderson** [comment]
Lindsay did some work subsetting the IPHC *set locations* to those that overlap the HBLL grid and then fitting and predicting on the HBLL grid. That doesn't appear to make much of a difference either.

<img width="543" alt="image" src="https://github.com/pbs-assess/dogfish-assess/assets/19349/cdc161d9-0fdf-4599-be42-540cc022aa17">


<img width="798" alt="Screenshot of RStudio at Apr 2, 2024 at 2_14_40 PM" src="https://github.com/pbs-assess/dogfish-assess/assets/19349/e821e3ec-efcc-42c9-8c62-c7ad81e52bc6">

**Comment by quang-huynh** [comment]
Another quick check that the trends in mean CPUE don't really vary by substrate:

![hbll_substrate_year](https://github.com/pbs-assess/dogfish-assess/assets/15094006/316a5a1a-8601-4a82-b730-34a58dcbd0b0)
