### ISSUE TITLE
Consider discard mortality rate

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#16]
Currently assuming 100%.

In last assessment, 6% was used for longline and "5% for the first two hours of a trawl fishing event with 5% for each additional hour" for trawl (which is complicated to calculate, see below). 

Quotes from Res Doc:

> Discard mortality (tonnes) is calculated for longline fisheries using a 6% discard mortality rate applied to discards (tonnes).

> Discard mortality (tonnes) is calculated for trawl fisheries by applying the calculated annual weighted average discard mortality rate to discards (tonnes)

> mortality discard rates (%) from the Integrated Fisheries Management Plan (IFMP) for Pacific Canadian groundfish fisheries (DFO, 2009)

> For the trawl fishery, the IFMP uses 5% for the first two hours of a trawl fishing event with 5% for each additional hour (DFO, 2009). The application of tow duration-dependent discard mortality rate required trawl effort data. Prior to 1996, trawl data were rolled up by multiple fishing events, and tow duration for individual fishing events were not available. The average tow duration was calculated from the total number of hours and the number of fishing events within a roll-up for 1980-1995. Data from 1996 onwards were available on a tow by tow basis. A weighted average of the trips within each year (with the discards per trip as the weights) was used to estimate to annual trawl discard mortality rate (Tables 6 and 7). Missing years were interpolated from the prior year and the subsequent year. Trawl discard and effort data were not available for 1966-1979 to estimate annual discard mortality rates with equation 1. To obtain discard mortality rates for these years the average discard mortality for the subsequent ten years (1980-1989) was extrapolated back.

However, reviewers noted (quotes from Proceedings):

> in the U.S. fishery about 42% of female mortality and at least 80% of male mortality results from discarding and he raised concerns about the effects of underestimation of discards in the past, and the potential for future increases in the discard rate.

> These discard mortality estimates seem very low compared to Atlantic estimates.

**Comment by LindsayDavidson** [comment]
NWFS Dogfish assessment uses the following discard mortality rates and suggest further research is needed. 

"In the 2011 assessment, bottom and midwater trawl discard mortality were assumed to be 100%,
and non-trawl discard mortality to be 50%. Figure 18 shows spiny dogfish bycatch in an at-sea
hake trawl to support the assumption of 100% trawl discard morality. Since no new study of
dogfish discard mortality has been conducted since 2011, the same assumptions are made in this
assessment. Alternative assumptions regarding discard mortality by gear type were explored in
sensitivity analyses (see Section 2.5.1)."

**Comment by seananderson** [comment]
From Atlantic Canada [SAR](https://waves-vagues.dfo-mpo.gc.ca/library-bibliotheque/331375.pdf):

> There are a few available estimates for dogfish discarding mortality. Published
studies report discard mortalities of 0-29% for dogfish caught with OTB (otter trawl) (depending on catch
size), and 55% mortality for gillnet-caught fish. Therefore, dogfish discard mortality in Canadian
waters was calculated as per the following: 25% for OTB catches > 200 kg, 0% for OTB
catches < 200 kg, 55% for gillnet catches, 10% for longline catches, and 25% for purse seine
catches. The exact values are debatable, although all appear to be consistent with the
experimental values reported above and observer observations of the manner in which fishers
and their gear treat dogfish catch. Estimated dogfish discard mortality has averaged about 850
mt annually since 1986. Discard mortality often exceeded reported catch prior to 1999, but
recent landings have greatly exceeded discard mortality (Fig. 11). 

given the relatively low trawl values and the complicated calculation used last time, 100% for trawl may be a reasonable way forward

For longline... maybe 50% following NWFSC? We know they often aren't treated well. 6% is likely far too low. 10% also feels low?

**Comment by seananderson** [comment]
US West Coast last assessment:
> There are no studies performed on estimating discard mortality of spiny dogfish in the Northeast Pacific Ocean for neither bottom trawl nor non-trawl fleet. Many factors, such as trawl time, handling techniques, and time spent on the deck affect shark survival. In spiny dogfish assessments conducted elsewhere, assumed discard mortality rates ranged from 5% to 50% for bottom trawl and from 6% to 75% for non-trawl gears, but all sources noted considerable uncertainty in these estimates. In the 2011 assessment, bottom and midwater trawl discard mortality were assumed to be 100%, and non-trawl discard mortality to be 50%. Figure 18 shows spiny dogfish bycatch in an at-sea hake trawl to support the assumption of 100% trawl discard morality. Since no new study of dogfish discard mortality has been conducted since 2011, the same assumptions are made in this assessment. Alternative assumptions regarding discard mortality by gear type were explored in sensitivity analyses (see Section 2.5.1).

Alaska last assessment:
> Nearly all incidental shark catch in the BSAI and GOA is discarded (rates in Table 19.4). Mortality rates of discarded sharks are unknown but are conservatively estimated in this report as 100%. This assumption is supported by a study where 10 Pacific sleeper sharks were tagged after being caught on catcher vessels in the pollock trawl fishery. All 10 appeared dead at time of release or died shortly after (Tribuzio, unpublished data).

**Comment by seananderson** [comment]
US West Coast also did these sensitivities:

> We also explored the model sensitivity to the alternative assumptions regarding dogfish discard mortality. In the base model, 100% discard mortality was assumed for trawl discard fleet and 50% for hook-and-line discard. In the alternative runs, we assumed: • 100% discard mortality for bottom trawl and non-trawl discard fleets, • 50% discard mortality for bottom trawl and non-trawl discard fleets. • 35% discard mortality in non-trawl fleet. • 6% mortality for non-trawl discard fleet and 5% for bottom trawl discard fleet. This sensitivity was explored in 2011 assessment, because these discard mortality values were used by the Integrated Fisheries Management Plan (IFMP) for Pacific Canadian groundfish fisheries (except for the fact that IFMP uses 5% discard mortality for the first two hours of a trawl fishing event with 5% for each additional hour (no historical data on tow length were available for this assessment)).

**Comment by quang-huynh** [comment]
Here's what a quick Google Scholar search pulls up:

https://doi.org/10.1577/M06-071.1 (gillnets are more problematic than trawl, NW Atlantic)
https://doi.org/10.1111/jfb.13197 (Review paper on elasmobranch release mortality, may include dogfish?)
https://sedarweb.org/documents/sedar-39-dw-21-a-preliminary-review-of-post-release-live-discard-mortality-rate-estimates-in-sharks-for-use-in-sedar-39/ (See Table 3, p. 27, on the order of 10-50% mortality)
https://doi.org/10.1093/icesjms/fsl003 (Five percent mortality)
https://doi.org/10.1016/j.fishres.2006.10.001 (30 percent on bottom trawl)
