### ISSUE TITLE
TWG #2 follow-up

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/dogfish-assess#21]
Modeling:

- [x] Look at low base M scenario for both A and B models. State the M/K ratio in the various models
- [x] Add dome selectivity to SYN index. Smaller size comps than IPHC index

Writing:

- [x] Recommendations for research
- [x] Look at pre-COSEWIC TOR, eg., yelloweye rockfish, for inspiration to revise TOR
- [x] Summarize new information since 2010 and 1979 assessments. What can we say about updating the TAC?

**Comment by seananderson** [comment]
- [x] justify discard mortality assumptions and consider showing impact (or lack therefore) of not assuming 100% mortality (NWFSC does 100% trawl mortality, 50% longline)
