### ISSUE TITLE
Re-run MCMC for B2

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/dogfish-assess#25]

**Comment by seananderson** [comment]
Done but I still need to update the figures...

**Comment by quang-huynh** [comment]
Running this scripts should suffice: https://github.com/pbs-assess/dogfish-assess/blob/main/ss3/07-outside-ss3-posterior.R

There's an additional step of running `ss.exe -mceval` for the time series figures that I can assist with, if you send me the .psv files

**Comment by seananderson** [comment]
Done
