### ISSUE TITLE
COSEWIC metrics

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#28]
Modified from the inside yelloweye resdoc:

COSEWIC Metric A measures the probability that the stock has declined by 70%, 50% and 30%
after three generations

P70 - Probability that, on average, the stock declined below 70% of B1937 over three generations, where generation time is 38 years and probability is calculated as P[1 − B_recent/B1937 > 0.7].
2. P50 - Probability that, on average, the stock declined below 50% of B1937 over three generations.
3. P30 - Probability that, on average, the stock declined below 30% of B1937 over three generations.

COSEWIC Metric E measures the probability of future extinction of the stock. A stock is designated as endangered if the probability of extinction is 20% within 20 years (or five generations,
whichever is longer) and threatened if there is a 10% probability of extinction within 10 years.
Criteria E is seldom applied to marine fishes, due to heavy reliance on data, and assumptions
about parameters required as inputs to population viability analyses (Ross Claytor, COSEWIC,
pers.comm, January 29, 2020). Another requirement for estimating extinction risk involves setting
the threshold for extinction, which is not explicitly defined in the COSEWIC criteria (COSEWIC
2015).

In order to evaluate the probability of future extinction under candidate MPs, stock-specific
extinction thresholds must be assigned. Below these thresholds the stock would be considered
functionally extirpated or extinct. We propose two candidate extinction thresholds of 2%B0 and
5%B0.

**Comment by seananderson** [comment]
3 generations is very long... but virtually all models put P30 from 1937 at near 1.0 probability I believe

**Comment by quang-huynh** [comment]
Define the generation time to be 1/M + 50% maturity age = 46 years (M = 0.074, maturity = 33 years)

**Comment by quang-huynh** [comment]
Are we using the models or indices for COSEWIC metric A?

**Comment by seananderson** [comment]
Indices don’t go very far back, but perhaps we could do both, since even
the recent indexes are fairly steep and that provides a second line of
evidence that doesn’t require buying into the whole assessment.
