### ISSUE TITLE
Add description of sea lion trends and justify M scenarios

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#29]
We could use a paragraph summarizing what's happened with Steller (and California?) sea lions in BC and justifying the various time-varying M scenarios. There are the res docs and SARs to cite that we've previously looked at. I believe there's a new resdoc that just came out as well to grab from the CSAS site.

**Comment by seananderson** [comment]
Docs:

https://www.dfo-mpo.gc.ca/csas-sccs/Publications/SAR-AS/2020/2020_046-eng.html
https://www.dfo-mpo.gc.ca/csas-sccs/Publications/SAR-AS/2021/2021_035-eng.html

https://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2018/2018_006-eng.html

And the new one:
https://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2024/2024_047-eng.html

**Comment by LindsayDavidson** [comment]
I added a paragraph that includes Steller and California sea lions and Offshore killer whales. Starts around line 1574
