### ISSUE TITLE
Longline length selectivity curves are weird with US growth

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#32]
Try to fix if we have time.

**Comment by seananderson** [comment]
What it looks like with the x-axis extended to smaller dogfish: 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/7a595819-8dbe-4891-a053-259d2e485ab4">

One quick way to 'fix' this would be to mirror the params to something else, which may be preferable to the wonky curve estimated here?

**Comment by quang-huynh** [comment]
With US growth, the model fits the survey indices and comps better at the cost of the longline comps. See the `diff` column in the likelihood components:

![image](https://github.com/user-attachments/assets/35369786-24f2-436d-96be-27d42c6da2e0)

Increasing the weighting term to 0.25 (from the current value of 0.047) fixes the longline selectivity estimate and comp fit. However, the R0 estimate hits the upper bound (current B/B0 = 1). My impression is that the US growth parameters are incompatible with the data. However, it's not obvious why.

Unresolved for now.

**Comment by seananderson** [comment]
That's all good investigative work. I guess the remaining question is if we should drop it from any ensemble summary statistics or projection plots from the 'reference point' section onwards. My feeling is we probably should drop it at that point.
