### ISSUE TITLE
Update Table `tab:ss3-par` to report model A0

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#38]
Update caption and contents.

**Comment by quang-huynh** [comment]
@seananderson can you update the justification for the catch multipler values != 1 in the description column?

https://github.com/pbs-assess/dogfish-assess/blob/main/tables/ss3_par_annotate_dogfish.csv#L24

**Comment by seananderson** [comment]
To save having to maintain this, they now all say `Catch multiplier - accounts for discard mortality` and the caption notes: `Parameters labelled as \texttt{\_Mult} act as multipliers relating dead catch to observed catch. I.e., they are the reciprocal of the discard mortality rates from Table~\ref{tab:postdiscardrates}`.
