### ISSUE TITLE
Add discussion of indicators

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#40]
Quang: 
> What we want are indicators that could differentiate one vs the other since there are lags in the age structure (predicted IPHC, CPUE, synoptic indices)

Add in discussion? Maybe in triggers/timeline section towards end?

**Comment by quang-huynh** [comment]
This paragraph was added in Line 1665:

> There is no formal trigger we can recommend that would suggest an earlier than anticipated reassessment.
However, it will be important to monitor population indices and length distributions in the annual updates to the groundfish data synopsis report \citep{anderson2019synopsis, anderson2020synpaper, synopsis2021data, synopsis2022data}.
The population models presented here do slightly differ in the predicted recent index trend. With constant natural mortality, the index is predicted to be somewhat constant or with a slower rate of decline in recent years, compared to faster declines in models with increasing natural mortality (Figure ~\ref{fig:ss3-sens-m-fit}).
Thus, it will be important to revisit the model quickly if there are signs of faster than expected recovery in the survey indices or commercial CPUE. Rapid changes in the index trend or size distribution would warrant an evaluation of whether the data are representative of population trends or behavioural changes that affect catchability to the surveys.
