### ISSUE TITLE
Add rationale for why bottom trawl discard fleet is used as basis for selectivity mirroring

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#42]
- Longline Discards
- Recreational catch
- Salmon Bycatch (probably easiest to justify based on gillnets at least)

**Comment by quang-huynh** [comment]
Bottom trawl is the only source of composition data. For recreational and salmon fisheries, the gear presumably operates in surface waters and dome selectiivty is sensible from a behavioral perspective (older/larger fish in deep waters). 

Not sure about longline but this figure shows how little discards there are. Assumptions about selectivity likely has little impact on estimation on stock trend.

![catch_fleet_discard_landings](https://github.com/user-attachments/assets/f1e89794-6f92-43cd-965f-1736808e3a1d)

**Comment by seananderson** [comment]
Noted "Several other fleets mirror the selectivity of this fleet since it is the only discard fleet with length composition data."
