### ISSUE TITLE
Did IPHC survey catch dogfish in every set?

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/dogfish-assess#7]
Currently looking at some dataset summaries and saw that there are very few if any zero sets in the IPHC survey:

```
fit_iphc_nb2 <- readRDS("data/generated/iphc-nb2-sdmTMB_gfdata.rds")
dplyr::summarise(fit_iphc_nb2$data, n = n(), p = mean(N_it20 > 0), .by = year)
```

Presumably the zero sets got removed somewhere along the way?

**Comment by seananderson** [comment]
I’m pretty sure that’s real. Right, @LindsayDavidson ?
